#!/bin/sh

#---------------------------------------
#               Globals
#---------------------------------------
alias -g grey="ubuntu@3.0.101.215"
alias -g sbys="ubuntu@sbys.tk"
alias -g yeh="root@yehbackend.tk"
# alias -g s2="-i ~/.ssh/sweden.pem bitnami@18.237.198.158"

#---------------------------------------
#              MVPS
#---------------------------------------

alias ..="cd .."
alias a='adb connect 192.168.0.101'
alias c="clear"
alias cc="calcurse"
alias cLO="curl -LO"
alias cpr="cp -r"
alias t="git checkout -B test > /dev/null 2>&1"
alias d="doas --"
alias dau="doas -u $USER --"
alias dc="doas cfdisk"
alias dcpr="da cp -r"
alias dka="da killall"
alias dlf="da lf"
alias dm="doas mount"
alias dmd="da mkdir"
alias dmv="da mv"
alias drmr="da rm -r"
alias duf="da umount -f"
alias e="exit"
alias f="faint"
alias f3="faint -d 3"
alias f5="faint -d 5"
alias fl="faint -l"
alias fn="faint -n"
alias fr="flutter run"
alias g="bolt -g"
alias ka="killall"
alias l="launch -f"
alias m="git checkout master > /dev/null 2>&1"
alias M="neomutt 2>/dev/null"
alias md="mkdir"
alias ml="mpv --loop"
alias n="nvim5"
# alias n="XDG_CONFIG_HOME=/mnt/internal/downloads/lua nvim5"
# alias n="nvim5 --clean -S ~/.config/nvim/init.lua"
# alias n="newsboat"
alias p="git checkout personal > /dev/null 2>&1"
alias pg="ps aux | grep"
alias psp1="patch -s -p1"
alias rmr="rm -r"
alias s="bolt --search"
alias sshp="ssh -p \$PORT \$PHONE"
alias src=". ~/.config/zsh/functions && . ~/.config/zsh/aliases"
alias user="who | head -1 | cut -d' ' -f1"
alias v="nvim"
alias W="weechat"
alias x="xprop"
alias xek="xev -event keyboard"
alias xmqf="xdg-mime query filetype"
alias yda="youtube-dl -x --embed-thumbnail -f bestaudio/best"
alias ydv="youtube-dl -f best"
alias tra="transmission-remote -a"

# alias t=": >"
# yd="youtube-dl -x --audio-format mp3 --audio-quality 0"

#---------------------------------------
#              Pacman & Yay
#---------------------------------------

# alias dp="d pacman"
# alias dpS="dp -S"
# alias dpSn="dpS --needed"
# alias dpSnn="dpSn --noconfirm "
# alias dpSyu="dp -Syu"
# alias dpRns="dp -Rns"
# alias dpRnsn="dpRns --noconfirm"

alias pQs="pacman -Qs"
# alias pQqe="pacman -Qqe"

# alias expac="expac | sort -n"

# alias yS="yay -S"
# alias ySn="yS --needed"
# alias ySnn="ySn --noconfirm"

#---------------------------------------
#               Paru
#---------------------------------------

alias pSyu="paru -Syu"
alias pSyun="pSyu --noconfirm"
alias pS="paru -S"
alias pSn="pS --noconfirm"
alias pSnn="pS --noconfirm --needed"
alias pRns="paru -Rns"
alias pRnsn="pRns --noconfirm"

#---------------------------------------
#              Git
#---------------------------------------

alias gP="git pull"
alias gPr="git pull --rebase"
alias gPn="git pull --no-rebase"
alias gaa="git add ."
alias gb="git branch"
alias gbm="gb -m"
alias gba="gb -a"
alias gbD="gb -D"
alias gc="git checkout"
alias gcB="gc -B"
alias gcl="git clone"
alias gcan="git commit --amend --no-edit"
alias gd="git diff"
alias gi="git init"
alias glo="git log --oneline"
alias glogda="git log --oneline --graph --decorate --all"
alias gm="git merge"
alias gmn="git merge --no-ff"
alias gp="git push"
alias gpf="gp -f"
alias gpfo="gpf origin"
alias gpfom="gp -f origin master"
alias gpfop="gp -f origin personal"
alias gpo="gp origin"
alias gpod="gpo -d"
alias gpom="gpo master"
alias gpuo="gp -u origin"
alias gra="git remote add"
alias grc="git rebase --continue"
alias grh="git reset --hard"
alias grsuapo="git remote set-url --add --push origin"
alias gs="git stash"
alias gsc="git stash clear"
alias gsgsc="git stash && git stash clear"

# alias grH="git reset HEAD"
# alias gpsuo="git push --set-upstream origin"
# ug="cd $DF; git commit -a -m"update\" && git push -u origin master"


#---------------------------------------
#              Yarn
#---------------------------------------
alias y="yarn"
alias ya="y add"
alias yaD="ya -D"
alias yb="y build"
alias yc="y create"
alias yd="y dev"
alias yg="y generate"
alias yga="y global add"
alias yi="y init"
alias yiy="yi -y"
alias yl="y list"
alias ys="y start"
alias yt="y test"
alias ysa="ys --android"
alias yr="y remove"
alias yu="y upgrade"

#---------------------------------------
#              Make
#---------------------------------------
alias dmi="da make install"
alias dmc="da make clean"
alias dmci="da make clean install"
alias dmu="da make uninstall"

#---------------------------------------
#              Systemd
#---------------------------------------
alias dsd="da systemctl disable"
alias dse="da systemctl enable"
alias dsr="da systemctl reload"
alias dsR="da systemctl restart"
alias dss="da systemctl start"
alias dsS="da systemctl stop"
alias dsf="da systemctl --failed"
alias sab="systemd-analyze blame"
alias dj="da journalctl -p 3 -xb"

##---------------------------------------
##              Runit
##---------------------------------------
#alias dsu="da sv up"
#alias dsd="da sv down"
#alias dss="da sv status"

#---------------------------------------
# Misc
#---------------------------------------
alias ls="ls -hN --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

#---------------------------------------
#              Laravel
#---------------------------------------

alias ccppdll="composer create-project --prefer-dist laravel/laravel"
alias cda="composer dump-autoload"

alias pa="php artisan"
alias pas="pa serve"

# Make
alias pammo="pa make:model"
alias pammg="pa make:migration"
alias pammd="pa make:middleware"
alias pamc="pa make:controller"

# Migration
alias pam="pa migrate"
alias pamf="pa migrate:fresh"
alias pams="pa migrate:status"
alias pamr="pa migrate:rollback"

#---------------------------------------
#              Docker 
#---------------------------------------
# alias db="docker build"

# SSH
alias scii="ssh-copy-id -i $GIT/own/magpie-private/.ssh/id_rsa.pub"

#===============================================================================
#                             Exp
#===============================================================================

# # tmux
# alias ta="tmux attach || tmux"
# alias tl="tmux ls"

# # XBPS
# alias
#    dxi="da xbps-install"
#    dxis="da xbps-install -S"
#    dxisy="da xbps-install -Sy"
#    dxrry="da xbps-remove -Ry"
#    dxisuy="da xbps-install -Suy"
#    xqrs="xbps-query -Rs"

# # Flutter
# alias fr="flutter run"


# GPG
# alias gpgs="gpg -c --s2k-cipher-algo AES256 --s2k-digest-algo SHA512 --s2k-count 65536"

# # lsd
# alias l="lsd"
# alias ll="lsd -l"
# alias l1="lsd -1"
# alias lA1="lsd -1A"
# alias lAl="lsd -Al"
# alias lt="lsd --tree"
# alias lAt="lsd -A --tree"

# # Power
# alias sS='systemctl suspend'
# alias sH='systemctl hibernate'
# alias pku='pkill -KILL -u $USER'
# alias po='poweroff'
# alias rb='reboot'


# # Adb
# alias aps="adb push --sync"
# alias ai="adb install"

# # NPM
# alias ncra="npx create-react-app"

#---------------------------------------
#              NPM
#---------------------------------------
# alias niy="npm init -y"

# alias ni="npm install"
# alias nis="npm install --save"
# alias niD="npm install -D"
# alias dnig="da npm install -g"

# alias nrd="npm run dev"
# alias nrs="npm run start"
# alias nrt="npm run test"
# alias nrb="npm run build"

# alias nu="ncu -u"
