local map = require('map')

map('i', '\'i', '\'\'<left>')
map('i', '"i', '""<left>')
map('i', '`i', '``<left>')
map('i', '(i', '()<left>')
map('i', '{i', '{}<left>')
map('i', '[i', '[]<left>')
map('i', '<i', '<><left>')
map('i', '""i', '""""""<left><left><left>')

map('i', '\'a', '\'\'')
map('i', '"a', '""')
map('i', '`a', '``')
map('i', '(a', '()')
map('i', '{a', '{}')
map('i', '[a', '[]')
map('i', '<a', '<>')

map('i', '\'o', '\'<cr>\'<esc>O')
map('i', '"o', '"<cr>"<esc>O')
map('i', '`o', '`<cr>`<esc>O')
map('i', '(o', '(<cr>)<esc>O')
map('i', '{o', '{<cr>}<esc>O')
map('i', '[o', '[<cr>]<esc>O')
map('i', '""o', '"""<cr>"""<esc>O')
