#!/bin/sh
#          _         _  __
#   _  __ (_)____   (_)/ /_ _____ _____
#  | |/_// // __ \ / // __// ___// ___/
# _>  < / // / / // // /_ / /   / /_
#/_/|_|/_//_/ /_//_/ \__//_/    \___/
#
# X11 startup script

xset -b &            # Disable PC speaker
xset r rate 200 30 & # Speed key press delay & reapeat rate
{
    xmodmap "$LAYOUT_EN"
    xcape -e "Super_L=Escape;Mode_switch=Tab"
} &                                    # Bind Multi-purpose keys
xss-lock -n 'backlight -D' -- 'lock' & # Set Dimmer & Locker
xset s 300 300 &                       # Set Dimmer & Locker Delays
libinput-gestures &                    # Bind gesture commands
dunst &                                # Launch notification server
launch --tmux &                        # Launch tmux
echo "$DISPLAY" > /tmp/DISPLAY &       # For Udev & Fcron environment
xbanish &                              # Hide cursor when idle
xsetroot -cursor_name left_ptr &       # Remove the ugly X cursor
set-display                            # Switch to external monitor if connected
xrandr --dpi "$(get-dpi --pixel)"      # Set correct DPI
# lock                                   # Start locked

$COMPOSITOR &         # Launch Compositor
bluetoothctl power on # Turn bluetooth on
pipe
set-bg # Set the last used wallpaper
alacritty -e tmux a &
exec $WM # Launch Window Manager

#===============================================================================
#                             Exp
#===============================================================================

# xautolock -detectsleep -time 10 -locker 'savescreen' & # Set Screen Saver
# scratchpad &  # launch scratchpad
# backlight --max                   # Set maximum brightness
# qtile start # Launch Window Manager
# { sleep 5 && pkill dwm; } & # Fix uniblocks glithes
# $TERMINAL -e tmux attach & # Launch terminal
# $STATUSBAR &  # Launch Statusbar
# dbus-launch dunst &                                # Launch notification server
# /usr/lib/notification-daemon-1.0/notification-daemon & # Launch notification daemon
# bolt --generate &                # Generate search list for bolt
# xcape -e "Super_L=Escape;Super_R=backslash;Mode_switch=Tab"
# xset r rate 300 60 & # Speed key press delay & reapeat rate
# mirror --mail &                            # Sync mails
# pulseaudio --exit-idle-time -1 -D & # Fix pulseaduio bug
# toggle --wall-reel    # Start wallpaper reeling
# watchmen &                             # Launch inotify watchers
# sh -c "sleep 0.5;  stalonetray -bg \"#000000\" --geometry \"1x1+125+5\"" &
# xautolock -detectsleep -time 5 -locker lock & # Set Locker
# xidlehook --not-when-audio --not-when-fullscreen \
# --timer 60 'backlight -h' 'backlight -m' & # Set up dimmer
# xset s off &                                   # Turn off screen blanking
# xidlehook --not-when-audio --not-when-fullscreen \
# --timer 300 'lock' '' & # Set up locker
# gebaard -b # Bind gesture commands
