#!/bin/sh
#
# Config file for uniblocks

CONFIG="\
sys,panel -s,3;
wifi,panel -w,30;
vol,panel -v,0;
dt,panel -d,60;
"
# mail,panel -m,0;

DELIMITER=" "
# DELIMITER="      "

display() {
   xsetroot -name "$1"
}
